[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pymdstresslab"
version = "0.0.1"
authors = [{name="Author",email="author@mail.me"}]
description = "Python bindings for MDStressLab++"
